DLauritzForumUserBundle:
    resource: "@DLauritzForumUserBundle/Resources/config/routing.yml"
    prefix:   /

DLauritzForumForumBundle:
    resource: "@DLauritzForumForumBundle/Resources/config/routing.yml"
    prefix:   /

DLauritzForumAdminBundle:
    resource: "@DLauritzForumAdminBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login.{_format}
    defaults:
        _controller: DLauritzForumUserBundle:User:login
        _format: html
    requirements:
        _format: html|json|xml

login_check:
    pattern: /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
